version: "3.9"

services:
  db:
    image: postgres:16-alpine
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=root
      - POSTGRES_DB=zicare-clinic
    networks:
      - default
