basePath: /api/v1
definitions:
  dto.EmployeeLoginReq:
    properties:
      password:
        maxLength: 20
        minLength: 5
        type: string
      username:
        maxLength: 20
        minLength: 5
        type: string
    required:
    - password
    - username
    type: object
  dto.EmployeeRegisterReq:
    properties:
      password:
        maxLength: 20
        minLength: 5
        type: string
      username:
        maxLength: 20
        minLength: 5
        type: string
    required:
    - password
    - username
    type: object
  dto.ErrWebResponse:
    properties:
      code:
        type: integer
      detail: {}
      status:
        type: string
    type: object
  dto.SwLoginRes:
    properties:
      code:
        type: integer
      data:
        type: string
      status:
        type: string
    type: object
  dto.SwUserRegisterRes:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/dto.UserResponse'
      status:
        type: string
    type: object
  dto.UserLoginReq:
    properties:
      email:
        type: string
      password:
        maxLength: 32
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  dto.UserRegisterReq:
    properties:
      address:
        maxLength: 128
        minLength: 8
        type: string
      birth:
        maxLength: 10
        minLength: 10
        type: string
      email:
        type: string
      gender:
        maxLength: 6
        minLength: 4
        type: string
      name:
        maxLength: 32
        minLength: 3
        type: string
      password:
        maxLength: 32
        minLength: 6
        type: string
      phone:
        maxLength: 13
        minLength: 10
        type: string
    required:
    - address
    - birth
    - email
    - gender
    - name
    - password
    - phone
    type: object
  dto.UserResponse:
    properties:
      address:
        type: string
      birth:
        type: string
      email:
        type: string
      gender:
        type: string
      name:
        type: string
      phone:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: zicare@mail.com
    name: Zi.Care
    url: www.zicare.com
  description: Application for managing clinic data and appointments
  license:
    name: Apache 2.0
  title: Zi.Care Clinic - API Documentation
  version: BETA
paths:
  /employee/login:
    post:
      consumes:
      - application/json
      description: Login for employee
      parameters:
      - description: Employee Credentials
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.EmployeeLoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SwLoginRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrWebResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrWebResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrWebResponse'
      summary: Employee Login
      tags:
      - Default
  /employee/register:
    post:
      consumes:
      - application/json
      description: Register new employee
      parameters:
      - description: Employee Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.EmployeeRegisterReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.SwUserRegisterRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrWebResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrWebResponse'
      summary: Employee Register
      tags:
      - Default
  /login:
    post:
      consumes:
      - application/json
      description: Login for patient
      parameters:
      - description: Patient Credentials
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.UserLoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SwLoginRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrWebResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrWebResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrWebResponse'
      summary: Patient Login
      tags:
      - Default
  /logout:
    get:
      consumes:
      - application/json
      description: Logout the currently authenticated user and clears the authorization
        cookie
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SwLoginRes'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrWebResponse'
      summary: Logout the user
      tags:
      - Default
  /register:
    post:
      consumes:
      - application/json
      description: Register new patient
      parameters:
      - description: Patient Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.UserRegisterReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.SwUserRegisterRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrWebResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrWebResponse'
      summary: Patient Register
      tags:
      - Default
swagger: "2.0"
