CREATE TABLE patients (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(100) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  gender VARCHAR(10) NOT NULL,
  address VARCHAR(255) NOT NULL,
  birth Date NOT NULL,
  created_at BIGINT NOT NULL DEFAULT (CAST (EXTRACT (EPOCH FROM CURRENT_TIMESTAMP) AS BIGINT)),
  updated_at BIGINT NOT NULL DEFAULT (CAST (EXTRACT (EPOCH FROM CURRENT_TIMESTAMP) AS BIGINT))
);